CREATE SCHEMA "gtm";
--> statement-breakpoint
CREATE TABLE "gtm"."cache" (
	"name" text NOT NULL,
	"hash" text NOT NULL,
	"value" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "cache_name_hash_pk" PRIMARY KEY("name","hash")
);
--> statement-breakpoint
CREATE TABLE "gtm"."profile_attempts" (
	"id" text PRIMARY KEY NOT NULL,
	"run_id" text NOT NULL,
	"entity_key" text NOT NULL,
	"operation" text NOT NULL,
	"state" text NOT NULL,
	"reserved_micro" bigint NOT NULL,
	"cost_micro" bigint,
	"job_id" text,
	"response_json" jsonb,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gtm"."profile_inputs" (
	"workflow_id" text NOT NULL,
	"source_id" text NOT NULL,
	"row_id" text NOT NULL,
	"input_json" jsonb NOT NULL,
	"person_key" text,
	"first_observed_at" timestamp with time zone NOT NULL,
	"last_observed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "profile_inputs_workflow_id_source_id_row_id_pk" PRIMARY KEY("workflow_id","source_id","row_id")
);
--> statement-breakpoint
CREATE TABLE "gtm"."profile_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"workflow_id" text NOT NULL,
	"owner" text NOT NULL,
	"lease_until" timestamp with time zone NOT NULL,
	"state" text NOT NULL,
	"budget_micro" bigint NOT NULL,
	"spent_micro" bigint DEFAULT 0 NOT NULL,
	"reserved_micro" bigint DEFAULT 0 NOT NULL,
	"input_json" jsonb NOT NULL,
	"companies_json" jsonb,
	"omitted" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gtm"."profile_work" (
	"run_id" text NOT NULL,
	"phase" text NOT NULL,
	"entity_key" text NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	CONSTRAINT "profile_work_run_id_phase_entity_key_pk" PRIMARY KEY("run_id","phase","entity_key")
);
--> statement-breakpoint
CREATE TABLE "gtm"."companies" (
	"key" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"enriched_at" timestamp with time zone,
	"last_attempt_at" timestamp with time zone,
	"enrichment_status" text,
	"error" text,
	"cost_usd" double precision,
	"sources_json" jsonb,
	"provenance_json" jsonb,
	"section_status_json" jsonb,
	"raw_responses_json" jsonb,
	"linkedin_url" text,
	"linkedin_slug" text,
	"linkedin_company_id" text,
	"name" text,
	"tagline" text,
	"description" text,
	"additional_information" text,
	"website_url" text,
	"domain" text,
	"email_domain" text,
	"industries_json" jsonb,
	"specialties_json" jsonb,
	"company_type" text,
	"ownership_status" text,
	"founded_on" text,
	"founded_year" integer,
	"company_size_label" text,
	"employee_count_min" integer,
	"employee_count_max" integer,
	"linkedin_employee_count" integer,
	"reported_employee_count" integer,
	"reported_employee_count_basis" text,
	"followers_count" integer,
	"headquarters_label" text,
	"headquarters_country_code" text,
	"headquarters_country" text,
	"headquarters_region" text,
	"headquarters_city" text,
	"headquarters_address" text,
	"headquarters_postal_code" text,
	"locations_json" jsonb,
	"country_codes_json" jsonb,
	"directions_urls_json" jsonb,
	"logo_url" text,
	"cover_image_url" text,
	"images_json" jsonb,
	"page_type" text,
	"is_active" boolean,
	"is_verified" boolean,
	"is_showcase" boolean,
	"is_paid_page" boolean,
	"is_auto_generated" boolean,
	"call_to_action_url" text,
	"jobs_url" text,
	"affiliated_pages_json" jsonb,
	"similar_companies_json" jsonb,
	"employee_previews_json" jsonb,
	"alumni_json" jsonb,
	"posts_preview_json" jsonb,
	"technologies_json" jsonb,
	"revenue_json" jsonb,
	"funding_json" jsonb,
	"investors_json" jsonb,
	"crunchbase_url" text,
	"stock_info_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "gtm"."people" (
	"key" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"enriched_at" timestamp with time zone,
	"last_attempt_at" timestamp with time zone,
	"enrichment_status" text,
	"error" text,
	"cost_usd" double precision,
	"sources_json" jsonb,
	"provenance_json" jsonb,
	"section_status_json" jsonb,
	"raw_responses_json" jsonb,
	"linkedin_url" text,
	"linkedin_slug" text,
	"linkedin_profile_id" text,
	"linkedin_numeric_id" text,
	"linkedin_urn" text,
	"full_name" text,
	"first_name" text,
	"last_name" text,
	"headline" text,
	"about" text,
	"industry" text,
	"primary_job_title" text,
	"primary_company_key" text,
	"job_function" text,
	"seniority" text,
	"location_label" text,
	"country_code" text,
	"country" text,
	"region" text,
	"city" text,
	"location_json" jsonb,
	"followers_count" integer,
	"connections_count" integer,
	"connections_count_kind" text,
	"recommendations_count" integer,
	"profile_photo_url" text,
	"cover_photo_url" text,
	"images_json" jsonb,
	"avatar_is_default" boolean,
	"is_open_to_work" boolean,
	"is_hiring" boolean,
	"is_premium" boolean,
	"is_influencer" boolean,
	"is_creator" boolean,
	"is_verified" boolean,
	"is_memorialized" boolean,
	"registered_at" text,
	"primary_locale" text,
	"locales_json" jsonb,
	"localized_headlines_json" jsonb,
	"profile_actions_json" jsonb,
	"message_option_type" text,
	"experiences_json" jsonb,
	"education_json" jsonb,
	"skills_json" jsonb,
	"languages_json" jsonb,
	"certifications_json" jsonb,
	"projects_json" jsonb,
	"volunteering_json" jsonb,
	"publications_json" jsonb,
	"patents_json" jsonb,
	"courses_json" jsonb,
	"honors_awards_json" jsonb,
	"organizations_json" jsonb,
	"recommendations_json" jsonb,
	"interests_json" jsonb,
	"causes_json" jsonb,
	"services_json" jsonb,
	"featured_json" jsonb,
	"websites_json" jsonb,
	"social_profiles_json" jsonb,
	"emails_json" jsonb,
	"phones_json" jsonb,
	"profile_highlights_json" jsonb,
	"related_profiles_json" jsonb,
	"posts_preview_json" jsonb,
	"activity_preview_json" jsonb
);
--> statement-breakpoint
CREATE TABLE "gtm"."profile_identifiers" (
	"entity" text NOT NULL,
	"namespace" text NOT NULL,
	"value" text NOT NULL,
	"key" text NOT NULL,
	CONSTRAINT "profile_identifiers_entity_namespace_value_pk" PRIMARY KEY("entity","namespace","value")
);
--> statement-breakpoint
CREATE TABLE "gtm"."gtm_viewer_grants" (
	"id" text PRIMARY KEY NOT NULL,
	"token_hash" text NOT NULL,
	"workflow_id" text NOT NULL,
	"workspace" text NOT NULL,
	"environment" text NOT NULL,
	"views" jsonb NOT NULL,
	"data_policy" text,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"token_ciphertext" text,
	CONSTRAINT "gtm_viewer_grants_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "profile_unsettled" ON "gtm"."profile_attempts" USING btree ("entity_key","operation") WHERE "gtm"."profile_attempts"."state" IN ('reserved','dispatched','uncertain');--> statement-breakpoint
CREATE UNIQUE INDEX "profile_single_flight" ON "gtm"."profile_runs" USING btree ((1)) WHERE "gtm"."profile_runs"."state" = 'running';--> statement-breakpoint
CREATE INDEX "companies_sources_gin" ON "gtm"."companies" USING gin ("sources_json" jsonb_path_ops);--> statement-breakpoint
CREATE INDEX "people_sources_gin" ON "gtm"."people" USING gin ("sources_json" jsonb_path_ops);--> statement-breakpoint
CREATE INDEX "people_experiences_gin" ON "gtm"."people" USING gin ("experiences_json" jsonb_path_ops);--> statement-breakpoint
CREATE INDEX "profile_identifiers_entity_key" ON "gtm"."profile_identifiers" USING btree ("entity","key");--> statement-breakpoint
CREATE UNIQUE INDEX "gtm_viewer_one_active_link" ON "gtm"."gtm_viewer_grants" USING btree ("workspace","environment","workflow_id") WHERE "gtm"."gtm_viewer_grants"."revoked_at" IS NULL AND "gtm"."gtm_viewer_grants"."token_ciphertext" IS NOT NULL;