import test from "node:test";
import assert from "node:assert/strict";
import { gatewayPlatformIdentity } from "../templates/lib/connections-platform";
import { connectionsApi } from "../templates/lib/connections-api";
import { connectionInventory } from "../templates/lib/connections-contract";
import { connectionsManagement } from "../templates/lib/connections-management";
import { CONNECTION_ACCESS_PROBE } from "../templates/lib/connections-access";

test("hosted inventory recognizes request identity without an API key or token environment variable", async (t) => {
  const env = { ...process.env }, symbol = Symbol.for("@vercel/request-context");
  const globals = globalThis as typeof globalThis & { [key: symbol]: unknown };
  const previous = globals[symbol];
  t.after(() => { process.env = env; if (previous === undefined) delete globals[symbol]; else globals[symbol] = previous; });
  process.env.VERCEL = "1";
  process.env.VERCEL_ENV = "production";
  process.env.VERCEL_PROJECT_ID = "prj_test";
  process.env.GTM_RUN_SECRET = "synthetic-read-secret";
  delete process.env.GTM_VIEWER_MODE;
  delete process.env.GTM_CONNECTIONS_ENABLED;
  delete process.env.VERCEL_OIDC_TOKEN;
  delete process.env.AI_GATEWAY_API_KEY;
  const token = "synthetic-request-identity-never-return";
  globals[symbol] = { get: () => ({ headers: { "x-vercel-oidc-token": token } }) };
  assert.equal(gatewayPlatformIdentity(), true);
  const workflows = [{ id: "qualify", title: "Qualify", connections: [{ connection: "AI_GATEWAY_API_KEY", provider: "TypeSafe" }] }];
  const response = await connectionsApi(new Request("https://private.example/api/connections", { headers: { authorization: "Bearer synthetic-read-secret" } }), workflows);
  assert.equal(response.status, 200);
  const body = await response.json();
  const row = body.connections.find((entry: { id: string }) => entry.id === "ai-gateway");
  assert.equal(row.name, "AI Gateway");
  assert.equal(row.configured, true);
  assert.equal(row.platformIdentity, true);
  assert.deepEqual(row.fields, []);
  assert.deepEqual(row.usage, [{ workflowId: "qualify", title: "Qualify", provider: "TypeSafe" }]);
  assert.ok(!JSON.stringify(body).includes(token));
  assert.equal((await connectionsApi(new Request("https://private.example/api/connections"), workflows)).status, 401);
  Object.assign(process.env, { GTM_CONNECTIONS_ENABLED: "1", GTM_VIEWER_PROTECTED: "1", GTM_CONNECTIONS_ORIGIN: "https://private.example", GTM_CONNECTIONS_TEAM_ID: "team_test", GTM_CONNECTIONS_VERCEL_TOKEN: "synthetic-management-token" });
  const fetcher = globalThis.fetch;
  t.after(() => { globalThis.fetch = fetcher; });
  globalThis.fetch = async (url, init) => {
    if (String(url).endsWith("/api/connection-access")) return new Response(init?.headers ? CONNECTION_ACCESS_PROBE : "", { status: init?.headers ? 200 : 401 });
    if (String(url).includes("/env?")) return Response.json({ envs: [] });
    return Response.json({ error: "synthetic unavailable deployment" }, { status: 503 });
  };
  const claims = { sub: "sso-protection", userId: "human", ownerId: "team_test", aud: "private.example" };
  const cookie = `_vercel_jwt=${Buffer.from("{}").toString("base64url")}.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.synthetic`;
  const management = await connectionsManagement(new Request("https://private.example/api/connection-management", { headers: { cookie } }), workflows);
  assert.equal(management.status, 200);
  const inventory = await management.json();
  assert.equal(inventory.connections.length, 1);
  assert.equal(inventory.connections[0].status, "Provided by Vercel");
  assert.deepEqual(inventory.connections[0].fields, []);
  assert.ok(!JSON.stringify(inventory).includes(token));
  process.env.GTM_VIEWER_MODE = "share";
  assert.equal(gatewayPlatformIdentity(), false);
  delete process.env.GTM_VIEWER_MODE;
  delete globals[symbol];
  assert.equal(gatewayPlatformIdentity(), false);
  process.env.VERCEL_OIDC_TOKEN = "synthetic-environment-identity";
  assert.equal(gatewayPlatformIdentity(), true);
  delete process.env.VERCEL;
  assert.equal(gatewayPlatformIdentity(), false);
});

test("platform usage preserves unknown declarations and accepts explicit gateway identity", () => {
  const rows = connectionInventory([], [{ id: "unknown", title: "Unknown" }, { id: "known", title: "Known", connections: [{ connection: "ai-gateway" }] }], true);
  assert.equal(rows[0].usageComplete, false);
  assert.deepEqual(rows[0].usage, [{ workflowId: "known", title: "Known" }]);
  assert.deepEqual(connectionInventory([], [], false), []);
});
