import { sql } from "drizzle-orm";
import { boolean, doublePrecision, index, integer, jsonb, primaryKey, text, timestamp } from "drizzle-orm/pg-core";
import { gtm } from "./gtm";

/**
 * Shared profiles. System times are timestamptz; registered_at and founded_on stay text because
 * providers send partial dates. Identity lives in profile_identifiers, so the LinkedIn columns are display only.
 */
export const people = gtm.table(
  "people",
  {
    key: text("key").primaryKey(),
    created_at: timestamp("created_at", { withTimezone: true }).notNull(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull(),
    enriched_at: timestamp("enriched_at", { withTimezone: true }),
    last_attempt_at: timestamp("last_attempt_at", { withTimezone: true }),
    enrichment_status: text("enrichment_status"),
    error: text("error"),
    cost_usd: doublePrecision("cost_usd"),
    sources_json: jsonb("sources_json"),
    provenance_json: jsonb("provenance_json"),
    section_status_json: jsonb("section_status_json"),
    raw_responses_json: jsonb("raw_responses_json"),
    linkedin_url: text("linkedin_url"),
    linkedin_slug: text("linkedin_slug"),
    linkedin_profile_id: text("linkedin_profile_id"),
    linkedin_numeric_id: text("linkedin_numeric_id"),
    linkedin_urn: text("linkedin_urn"),
    full_name: text("full_name"),
    first_name: text("first_name"),
    last_name: text("last_name"),
    headline: text("headline"),
    about: text("about"),
    industry: text("industry"),
    primary_job_title: text("primary_job_title"),
    primary_company_key: text("primary_company_key"),
    job_function: text("job_function"),
    seniority: text("seniority"),
    location_label: text("location_label"),
    country_code: text("country_code"),
    country: text("country"),
    region: text("region"),
    city: text("city"),
    location_json: jsonb("location_json"),
    followers_count: integer("followers_count"),
    connections_count: integer("connections_count"),
    connections_count_kind: text("connections_count_kind"),
    recommendations_count: integer("recommendations_count"),
    profile_photo_url: text("profile_photo_url"),
    cover_photo_url: text("cover_photo_url"),
    images_json: jsonb("images_json"),
    avatar_is_default: boolean("avatar_is_default"),
    is_open_to_work: boolean("is_open_to_work"),
    is_hiring: boolean("is_hiring"),
    is_premium: boolean("is_premium"),
    is_influencer: boolean("is_influencer"),
    is_creator: boolean("is_creator"),
    is_verified: boolean("is_verified"),
    is_memorialized: boolean("is_memorialized"),
    registered_at: text("registered_at"),
    primary_locale: text("primary_locale"),
    locales_json: jsonb("locales_json"),
    localized_headlines_json: jsonb("localized_headlines_json"),
    profile_actions_json: jsonb("profile_actions_json"),
    message_option_type: text("message_option_type"),
    experiences_json: jsonb("experiences_json"),
    education_json: jsonb("education_json"),
    skills_json: jsonb("skills_json"),
    languages_json: jsonb("languages_json"),
    certifications_json: jsonb("certifications_json"),
    projects_json: jsonb("projects_json"),
    volunteering_json: jsonb("volunteering_json"),
    publications_json: jsonb("publications_json"),
    patents_json: jsonb("patents_json"),
    courses_json: jsonb("courses_json"),
    honors_awards_json: jsonb("honors_awards_json"),
    organizations_json: jsonb("organizations_json"),
    recommendations_json: jsonb("recommendations_json"),
    interests_json: jsonb("interests_json"),
    causes_json: jsonb("causes_json"),
    services_json: jsonb("services_json"),
    featured_json: jsonb("featured_json"),
    websites_json: jsonb("websites_json"),
    social_profiles_json: jsonb("social_profiles_json"),
    emails_json: jsonb("emails_json"),
    phones_json: jsonb("phones_json"),
    profile_highlights_json: jsonb("profile_highlights_json"),
    related_profiles_json: jsonb("related_profiles_json"),
    posts_preview_json: jsonb("posts_preview_json"),
    activity_preview_json: jsonb("activity_preview_json"),
  },
  (table) => [
    index("people_sources_gin").using("gin", sql`${table.sources_json} jsonb_path_ops`),
    index("people_experiences_gin").using("gin", sql`${table.experiences_json} jsonb_path_ops`),
  ],
);

export const companies = gtm.table(
  "companies",
  {
    key: text("key").primaryKey(),
    created_at: timestamp("created_at", { withTimezone: true }).notNull(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull(),
    enriched_at: timestamp("enriched_at", { withTimezone: true }),
    last_attempt_at: timestamp("last_attempt_at", { withTimezone: true }),
    enrichment_status: text("enrichment_status"),
    error: text("error"),
    cost_usd: doublePrecision("cost_usd"),
    sources_json: jsonb("sources_json"),
    provenance_json: jsonb("provenance_json"),
    section_status_json: jsonb("section_status_json"),
    raw_responses_json: jsonb("raw_responses_json"),
    linkedin_url: text("linkedin_url"),
    linkedin_slug: text("linkedin_slug"),
    linkedin_company_id: text("linkedin_company_id"),
    name: text("name"),
    tagline: text("tagline"),
    description: text("description"),
    additional_information: text("additional_information"),
    website_url: text("website_url"),
    domain: text("domain"),
    email_domain: text("email_domain"),
    industries_json: jsonb("industries_json"),
    specialties_json: jsonb("specialties_json"),
    company_type: text("company_type"),
    ownership_status: text("ownership_status"),
    founded_on: text("founded_on"),
    founded_year: integer("founded_year"),
    company_size_label: text("company_size_label"),
    employee_count_min: integer("employee_count_min"),
    employee_count_max: integer("employee_count_max"),
    linkedin_employee_count: integer("linkedin_employee_count"),
    reported_employee_count: integer("reported_employee_count"),
    reported_employee_count_basis: text("reported_employee_count_basis"),
    followers_count: integer("followers_count"),
    headquarters_label: text("headquarters_label"),
    headquarters_country_code: text("headquarters_country_code"),
    headquarters_country: text("headquarters_country"),
    headquarters_region: text("headquarters_region"),
    headquarters_city: text("headquarters_city"),
    headquarters_address: text("headquarters_address"),
    headquarters_postal_code: text("headquarters_postal_code"),
    locations_json: jsonb("locations_json"),
    country_codes_json: jsonb("country_codes_json"),
    directions_urls_json: jsonb("directions_urls_json"),
    logo_url: text("logo_url"),
    cover_image_url: text("cover_image_url"),
    images_json: jsonb("images_json"),
    page_type: text("page_type"),
    is_active: boolean("is_active"),
    is_verified: boolean("is_verified"),
    is_showcase: boolean("is_showcase"),
    is_paid_page: boolean("is_paid_page"),
    is_auto_generated: boolean("is_auto_generated"),
    call_to_action_url: text("call_to_action_url"),
    jobs_url: text("jobs_url"),
    affiliated_pages_json: jsonb("affiliated_pages_json"),
    similar_companies_json: jsonb("similar_companies_json"),
    employee_previews_json: jsonb("employee_previews_json"),
    alumni_json: jsonb("alumni_json"),
    posts_preview_json: jsonb("posts_preview_json"),
    technologies_json: jsonb("technologies_json"),
    revenue_json: jsonb("revenue_json"),
    funding_json: jsonb("funding_json"),
    investors_json: jsonb("investors_json"),
    crunchbase_url: text("crunchbase_url"),
    stock_info_json: jsonb("stock_info_json"),
  },
  (table) => [index("companies_sources_gin").using("gin", sql`${table.sources_json} jsonb_path_ops`)],
);

/** One owner per identifier, for both entities. The store writes it in the same transaction as the record. */
export const profileIdentifiers = gtm.table(
  "profile_identifiers",
  {
    entity: text("entity").notNull(),
    namespace: text("namespace").notNull(),
    value: text("value").notNull(),
    key: text("key").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.entity, table.namespace, table.value] }),
    index("profile_identifiers_entity_key").on(table.entity, table.key),
  ],
);
