// Materialize the shared contract for the viewer's static registry reader.
import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
const [id, path] = process.argv.slice(2);
if (!id || !/^[0-9a-f-]{36}$/.test(id) || !path)
  throw new Error(
    "Usage: node scripts/profile-view.mjs <persistent-workflow-uuid> <output.data.ts>",
  );
await build({
  entryPoints: ["lib/profiles/view.ts"],
  outfile: "node_modules/.gtm-profiles/view.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  packages: "external",
});
const { profileView } = await import("../node_modules/.gtm-profiles/view.mjs");
const view = profileView(id);
await writeFile(
  path,
  `// Generated by scripts/profile-view.mjs. Regenerate when the shared contract changes.\nimport type { WorkflowData } from "../lib/data-api";\nimport type { DataPolicy } from "../lib/viewer-contract";\nexport const data: WorkflowData = ${JSON.stringify(view.data, null, 2)};\nexport const sharePolicy: DataPolicy = ${JSON.stringify(view.sharePolicy, null, 2)};\n`,
);
