import companyResearch from "./company-research";

/** Registry by name: agent stages name skills and get their text appended to the instructions. Regenerated by Upgrade. */
export const skills: Record<string, string> = {
  "company-research": companyResearch,
};
