import { cache } from "./cache";
import { exampleResearch } from "./example-research";
import { exampleScores } from "./example-scores";

export { cache, exampleResearch, exampleScores };
/** Registry by name: steps receive table names (strings) and resolve them here. Regenerated by Upgrade. */
export const tables = { cache, exampleResearch, exampleScores };
