import { exampleResearch } from "./example-research";
import { exampleScores } from "./example-scores";

export { exampleResearch, exampleScores };
/** Workspace result tables by name. Runtime tables (people, companies, cache, …) live in lib/tables.ts. Regenerated by Upgrade. */
export const tables = { exampleResearch, exampleScores };
