import { z } from "zod";
import { sectionValidators } from "./sections";

// The Drizzle definitions are the only schema: lib/schema/profiles.ts. These maps name each field's kind for validation and display.
export { people, companies } from "../schema/profiles";
export { identityFields } from "./identifiers.mjs";

export const peopleFields = {
  key: "TEXT",
  created_at: "TIME",
  updated_at: "TIME",
  enriched_at: "TIME",
  last_attempt_at: "TIME",
  enrichment_status: "TEXT",
  error: "TEXT",
  cost_usd: "REAL",
  sources_json: "JSON[]",
  provenance_json: "JSON{}",
  section_status_json: "JSON{}",
  raw_responses_json: "JSON{}",
  linkedin_url: "TEXT",
  linkedin_slug: "TEXT",
  linkedin_profile_id: "TEXT",
  linkedin_numeric_id: "TEXT",
  linkedin_urn: "TEXT",
  full_name: "TEXT",
  first_name: "TEXT",
  last_name: "TEXT",
  headline: "TEXT",
  about: "TEXT",
  industry: "TEXT",
  primary_job_title: "TEXT",
  primary_company_key: "TEXT",
  job_function: "TEXT",
  seniority: "TEXT",
  location_label: "TEXT",
  country_code: "TEXT",
  country: "TEXT",
  region: "TEXT",
  city: "TEXT",
  location_json: "JSON{}",
  followers_count: "INTEGER",
  connections_count: "INTEGER",
  connections_count_kind: "TEXT",
  recommendations_count: "INTEGER",
  profile_photo_url: "TEXT",
  cover_photo_url: "TEXT",
  images_json: "JSON{}",
  avatar_is_default: "BOOL",
  is_open_to_work: "BOOL",
  is_hiring: "BOOL",
  is_premium: "BOOL",
  is_influencer: "BOOL",
  is_creator: "BOOL",
  is_verified: "BOOL",
  is_memorialized: "BOOL",
  registered_at: "TEXT",
  primary_locale: "TEXT",
  locales_json: "JSON[]",
  localized_headlines_json: "JSON[]",
  profile_actions_json: "JSON[]",
  message_option_type: "TEXT",
  experiences_json: "JSON[]",
  education_json: "JSON[]",
  skills_json: "JSON[]",
  languages_json: "JSON[]",
  certifications_json: "JSON[]",
  projects_json: "JSON[]",
  volunteering_json: "JSON[]",
  publications_json: "JSON[]",
  patents_json: "JSON[]",
  courses_json: "JSON[]",
  honors_awards_json: "JSON[]",
  organizations_json: "JSON[]",
  recommendations_json: "JSON[]",
  interests_json: "JSON[]",
  causes_json: "JSON[]",
  services_json: "JSON{}",
  featured_json: "JSON{}",
  websites_json: "JSON[]",
  social_profiles_json: "JSON[]",
  emails_json: "JSON[]",
  phones_json: "JSON[]",
  profile_highlights_json: "JSON{}",
  related_profiles_json: "JSON[]",
  posts_preview_json: "JSON[]",
  activity_preview_json: "JSON[]",
} as const;
export const companiesFields = {
  key: "TEXT",
  created_at: "TIME",
  updated_at: "TIME",
  enriched_at: "TIME",
  last_attempt_at: "TIME",
  enrichment_status: "TEXT",
  error: "TEXT",
  cost_usd: "REAL",
  sources_json: "JSON[]",
  provenance_json: "JSON{}",
  section_status_json: "JSON{}",
  raw_responses_json: "JSON{}",
  linkedin_url: "TEXT",
  linkedin_slug: "TEXT",
  linkedin_company_id: "TEXT",
  name: "TEXT",
  tagline: "TEXT",
  description: "TEXT",
  additional_information: "TEXT",
  website_url: "TEXT",
  domain: "TEXT",
  email_domain: "TEXT",
  industries_json: "JSON[]",
  specialties_json: "JSON[]",
  company_type: "TEXT",
  ownership_status: "TEXT",
  founded_on: "TEXT",
  founded_year: "INTEGER",
  company_size_label: "TEXT",
  employee_count_min: "INTEGER",
  employee_count_max: "INTEGER",
  linkedin_employee_count: "INTEGER",
  reported_employee_count: "INTEGER",
  reported_employee_count_basis: "TEXT",
  followers_count: "INTEGER",
  headquarters_label: "TEXT",
  headquarters_country_code: "TEXT",
  headquarters_country: "TEXT",
  headquarters_region: "TEXT",
  headquarters_city: "TEXT",
  headquarters_address: "TEXT",
  headquarters_postal_code: "TEXT",
  locations_json: "JSON[]",
  country_codes_json: "JSON[]",
  directions_urls_json: "JSON[]",
  logo_url: "TEXT",
  cover_image_url: "TEXT",
  images_json: "JSON{}",
  page_type: "TEXT",
  is_active: "BOOL",
  is_verified: "BOOL",
  is_showcase: "BOOL",
  is_paid_page: "BOOL",
  is_auto_generated: "BOOL",
  call_to_action_url: "TEXT",
  jobs_url: "TEXT",
  affiliated_pages_json: "JSON[]",
  similar_companies_json: "JSON[]",
  employee_previews_json: "JSON[]",
  alumni_json: "JSON{}",
  posts_preview_json: "JSON[]",
  technologies_json: "JSON[]",
  revenue_json: "JSON{}",
  funding_json: "JSON{}",
  investors_json: "JSON[]",
  crunchbase_url: "TEXT",
  stock_info_json: "JSON{}",
} as const;
export type Entity = "people" | "companies";
export const fieldsFor = (entity: Entity): Record<string, string> =>
  entity === "people" ? peopleFields : companiesFields;
const validators: Record<string, z.ZodTypeAny> = {
  TEXT: z.string(),
  TIME: z.date(),
  INTEGER: z.number().int().nonnegative(),
  REAL: z.number().finite().nonnegative(),
  BOOL: z.boolean(),
  "JSON[]": z.array(z.unknown()),
  "JSON{}": z.record(z.string(), z.unknown()),
};
const experience = z
  .object({
    experience_key: z.string().min(1),
    company_key: z.string().nullable(),
    company_name: z.string().nullable(),
    title: z.string().nullable(),
    start_date: z.string().nullable(),
    end_date: z.string().nullable(),
    current_status: z.enum(["current", "ended", "unknown"]),
    current_status_evidence: z.unknown(),
    company_linkedin_id: z.string().nullable().optional(),
    company_linkedin_url: z.string().nullable().optional(),
    company_domain: z.string().nullable().optional(),
    is_primary: z.boolean().nullable().optional(),
  })
  .passthrough();
const membership = z
  .object({
    workflow_id: z.string().min(1),
    source_id: z.string().min(1),
    source_row_id: z.string().min(1),
    first_observed_at: z.string(),
    last_observed_at: z.string(),
  })
  .passthrough();
export function validateFields(
  entity: Entity,
  values: Record<string, unknown>,
) {
  const fields = fieldsFor(entity);
  for (const [key, value] of Object.entries(values)) {
    if (!Object.hasOwn(fields, key))
      throw new Error(`Unknown ${entity} field: ${key}`);
    if (value !== null) {
      validators[fields[key]].parse(value);
      sectionValidators[key]?.parse(value);
    }
    if (value !== null && key === "experiences_json")
      z.array(experience).parse(value);
    if (value !== null && key === "sources_json")
      z.array(membership).parse(value);
  }
  return values;
}
