#!/usr/bin/env python3
"""Regenerate the root README skills catalog from SKILL.md metadata."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Any

from gtm_validation_common import YamlLoadError, load_yaml_file, load_yaml_text
import validate_skill_metadata


MARKER_START = "<!-- skills-catalog:start -->"
MARKER_END = "<!-- skills-catalog:end -->"
DEFAULT_INSERT_BEFORE = "\n## Repository shape\n"


@dataclass(frozen=True)
class SkillCatalogEntry:
    name: str
    path: Path
    description: str
    function_tags: list[str]
    role_tags: list[str]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="repository root to update")
    parser.add_argument(
        "--taxonomy",
        type=Path,
        default=None,
        help="taxonomy YAML path; defaults to <repo>/docs/taxonomy.yaml",
    )
    args = parser.parse_args(argv)

    repo = args.repo.resolve()
    taxonomy_path = (args.taxonomy or repo / "docs" / "taxonomy.yaml").resolve()
    readme_path = repo / "README.md"

    validation_args = ["--repo", str(repo), "--taxonomy", str(taxonomy_path), "--quiet"]
    if validate_skill_metadata.main(validation_args) != 0:
        print("Refusing to generate README catalog because skill metadata validation failed.", file=sys.stderr)
        return 1

    try:
        taxonomy = load_yaml_file(taxonomy_path)
        entries = _load_skill_entries(repo)
        catalog = _render_catalog(entries, _taxonomy_function_tags(taxonomy))
        readme = readme_path.read_text(encoding="utf-8")
        updated = _replace_catalog(readme, catalog)
        readme_path.write_text(updated, encoding="utf-8")
    except (OSError, ValueError, YamlLoadError) as exc:
        print(f"README catalog generation failed: {exc}", file=sys.stderr)
        return 1

    print(f"Updated {readme_path.relative_to(repo)} skills catalog from {len(entries)} skill(s).")
    return 0


def _load_skill_entries(repo: Path) -> list[SkillCatalogEntry]:
    entries: list[SkillCatalogEntry] = []
    for path in sorted((repo / "skills").glob("*/SKILL.md")):
        frontmatter = load_yaml_text(_extract_frontmatter(path), path)
        if not isinstance(frontmatter, dict):
            raise ValueError(f"{path}: frontmatter must be a mapping")
        metadata = frontmatter.get("metadata")
        if not isinstance(metadata, dict):
            raise ValueError(f"{path}: metadata must be a mapping")
        entries.append(
            SkillCatalogEntry(
                name=_string(frontmatter, "name", path),
                path=path.relative_to(repo),
                description=_normalize_description(_string(frontmatter, "description", path)),
                function_tags=_string_list(metadata, "function_tags", path),
                role_tags=_string_list(metadata, "role_tags", path),
            )
        )
    return entries


def _extract_frontmatter(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: SKILL.md must start with YAML frontmatter delimiter '---'")
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "\n".join(lines[1:index])
    raise ValueError(f"{path}: frontmatter is missing closing delimiter '---'")


def _string(data: dict[str, Any], field: str, path: Path) -> str:
    value = data.get(field)
    if not isinstance(value, str):
        raise ValueError(f"{path}: {field} must be a string")
    return value


def _string_list(data: dict[str, Any], field: str, path: Path) -> list[str]:
    value = data.get(field)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"{path}: metadata.{field} must be a list of strings")
    return value


def _taxonomy_function_tags(taxonomy: Any) -> list[str]:
    if not isinstance(taxonomy, dict):
        raise ValueError("taxonomy must be a mapping")
    function_tags = taxonomy.get("function_tags")
    if not isinstance(function_tags, list) or not all(isinstance(tag, str) for tag in function_tags):
        raise ValueError("taxonomy.function_tags must be a list of strings")
    return function_tags


def _normalize_description(description: str) -> str:
    return " ".join(description.split())


def _render_catalog(entries: list[SkillCatalogEntry], function_tags: list[str]) -> str:
    lines = [
        "Generated by `python3 scripts/generate_readme_catalog.py`. Do not edit this block by hand.",
        "",
        "Skills are grouped by `function_tags`; skills with multiple function tags appear in multiple groups.",
    ]
    if not entries:
        lines.extend(["", "No skills are currently available."])
        return "\n".join(lines)

    for function_tag in function_tags:
        matching = sorted(
            (entry for entry in entries if function_tag in entry.function_tags),
            key=lambda entry: entry.name,
        )
        if not matching:
            continue
        lines.extend(["", f"### {_display_tag(function_tag)}", ""])
        for entry in matching:
            roles = ", ".join(f"`{role}`" for role in entry.role_tags)
            lines.append(f"- **[{entry.name}]({entry.path.as_posix()})** — {entry.description} Roles: {roles}.")
    return "\n".join(lines)


def _display_tag(tag: str) -> str:
    return " ".join(part.capitalize() for part in tag.split("-"))


def _replace_catalog(readme: str, catalog: str) -> str:
    block = f"{MARKER_START}\n{catalog}\n{MARKER_END}"
    has_start = MARKER_START in readme
    has_end = MARKER_END in readme
    if has_start != has_end:
        raise ValueError(f"README.md must contain both {MARKER_START} and {MARKER_END}")
    if not has_start:
        section = f"## Skills catalog\n\n{block}\n\n"
        if DEFAULT_INSERT_BEFORE in readme:
            return readme.replace(DEFAULT_INSERT_BEFORE, f"\n{section}## Repository shape\n", 1)
        suffix = "" if readme.endswith("\n") else "\n"
        return f"{readme}{suffix}\n{section}".rstrip() + "\n"

    start_index = readme.index(MARKER_START)
    end_index = readme.index(MARKER_END)
    if start_index > end_index:
        raise ValueError(f"README.md has {MARKER_END} before {MARKER_START}")
    end_index += len(MARKER_END)
    return f"{readme[:start_index]}{block}{readme[end_index:]}"


if __name__ == "__main__":
    raise SystemExit(main())
