import { defaultInput as exampleResearchInput, exampleResearch } from "./example-research";
import { defaultInput as exampleScoresInput, exampleScores } from "./example-scores";

/** Registry by slug: maintained by Create and Delete, regenerated by Upgrade. */
export const workflows = {
  "example-research": { run: exampleResearch, defaultInput: exampleResearchInput },
  "example-scores": { run: exampleScores, defaultInput: exampleScoresInput },
};
