import { defaultInput as exampleScoresInput, exampleScores } from "./example-scores";

/** Registry by slug: maintained by Create and Delete, regenerated by Upgrade. */
export const workflows = {
  "example-scores": { run: exampleScores, defaultInput: exampleScoresInput },
};
