import {
  viewer as exampleResearchViewer,
  data as exampleResearchData,
} from "./example-research.viewer";
import {
  viewer as exampleScoresViewer,
  data as exampleScoresData,
} from "./example-scores.viewer";
import {
  defaultInput as exampleResearchInput,
  exampleResearch,
} from "./example-research";
import {
  defaultInput as exampleScoresInput,
  exampleScores,
} from "./example-scores";

/** Registry by slug: maintained by Create and Delete, regenerated by Upgrade. */
export const workflows = {
  "example-research": {
    viewer: exampleResearchViewer,
    data: exampleResearchData,
    run: exampleResearch,
    defaultInput: exampleResearchInput,
  },
  "example-scores": {
    viewer: exampleScoresViewer,
    data: exampleScoresData,
    run: exampleScores,
    defaultInput: exampleScoresInput,
  },
};
